######################################################################
# Automatically generated by qmake (3.0) Mon Jul 6 13:07:36 2015
######################################################################

TEMPLATE = app
QT += widgets
TARGET = qt5_linux_dropped_frames_testcase
INCLUDEPATH += .

# Input
HEADERS += TestScene.h
SOURCES += main.cpp TestScene.cpp
